# **PROJETO DE ANÁLISE DE ENGAJAMENTO DE UM INSTAGRAM**
Projeto do curso Ciencia de dados impressionador da Hashtag Treinamentos

### O que queremos responder?
- Qual a tag mais engaja nessas publicações?
    - Agora queremos olhar apenas tags
<br><br>
- Ele também dá alguns direcionamentos:
    - Podem ignorar a coluna visualizações, queremos entender apenas curtidas, comentários e interações
    - Tags vazias é que realmente não possuem tag (favor tratar como vazio)

In [1]:
# Importando
import pandas as pd
import numpy as np

In [2]:
# Importar a base em excel
base = pd.read_excel("08. Analisando o engajamento no Instagram.xlsx")

In [3]:
# Apagando a coluna "Visualizações"
base = base.drop("Visualizações",axis=1)

In [4]:
# Visualizando novamente as 5 primeiras linhas
base.head()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,NaN,4437

In [5]:
# Agrupando por tags
base.groupby("Tags")["Curtidas"].mean()

Tags
Datas comemorativas                  17975.000000
Datas comemorativas/Promoções        29084.000000
Dicas de como usar/Novos Produtos     5703.500000
Dicas de como usar/Produtos           7586.666667
Influenciadores                      15197.285714
Loja                                  2832.500000
Loja/Produtos                         2930.000000
Novos Produtos                       11619.571429
Produtos                              5666.916667
Promoções                            26645.500000
Trends                               22400.666667
Trends/Produtos                      12894.000000
Name: Curtidas, dtype: float64

In [6]:
# Vamos usar isso para a nossa coluna "Tags"
# Transformando a coluna Tags em uma lista de tags
base.Tags = base.Tags.str.split("/")
base.head()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,[Loja],N,N,NaN,2874
1,Foto,2021-09-11,2930,28,"[Loja, Produtos]",N,N,NaN,2958
2,Foto,2021-09-11,2807,9,[Loja],N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,[Produtos],N,N,NaN,5164
4,Foto,2021-09-13,4392,45,[Produtos],S,N,NaN,4437

In [7]:
# Separando a coluna Tag em 1 linha para cada elemento da lista
base = base.explode('Tags')
base.head()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,Loja,N,N,NaN,2958
1,Foto,2021-09-11,2930,28,Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,NaN,5164

**cuidado pois as outras colunas serão duplicadas, então não podemos fazer o mesmo cálculo de média que estávamos fazendo**

In [8]:
# Repetindo o cálculo da média para pessoas
base.groupby('Pessoas')['Curtidas'].mean()

Pessoas
N     4154.615385
S    14100.574468
Name: Curtidas, dtype: float64

In [9]:
# Fazendo para Tag
base.groupby('Tags')['Curtidas'].mean()

Tags
Datas comemorativas    20752.250000
Dicas de como usar      6833.400000
Influenciadores        15197.285714
Loja                    2865.000000
Novos Produtos         10304.888889
Produtos                6269.823529
Promoções              27458.333333
Trends                 20024.000000
Name: Curtidas, dtype: float64

In [10]:
# Ordenando por curtidas
base.groupby("Tags")[["Curtidas","Comentários"]].mean().sort_values("Curtidas",ascending=False)

                         Curtidas  Comentários
Tags
Promoções            27458.333333   531.000000
Datas comemorativas  20752.250000   343.500000
Trends               20024.000000   352.250000
Influenciadores      15197.285714   161.714286
Novos Produtos       10304.888889   198.555556
Dicas de como usar    6833.400000   133.600000
Produtos              6269.823529    94.117647
Loja                  2865.000000    17.666667

In [11]:
# Filtrando valores sem tag
base.loc[base.Tags.isnull()]

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
11,Foto,2021-10-12,17831,391,NaN,S,S,NaN,18222
19,Foto,2021-12-12,16086,268,NaN,S,S,NaN,16354
29,Foto,2022-01-19,8612,142,NaN,S,N,NaN,8754
38,Foto,2022-02-15,17687,213,NaN,S,N,NaN,17900
41,Foto,2022-02-22,12530,90,NaN,S,N,NaN,12620
43,Foto,2022-03-04,24399,266,NaN,S,S,NaN,24665
49,Foto,2022-03-22,9087,106,NaN,S,S,NaN,9193
50,Foto,2022-03-26,16551,186,NaN,S,N,NaN,16737

In [12]:
# Atribuindo o texto sem tag para as colunas onde a tag é NaN
base.loc[base.Tags.isnull(),"Tags"] = "Sem Tag"

In [19]:
# Agora vamos atribuir o valor N para a coluna Carrosel
base.loc[base.Carrossel.isnull(),"Carrossel"] = "N"

In [14]:
base.loc[base.Tags.isnull()]

Empty DataFrame
Columns: [Tipo, Data, Curtidas, Comentários, Tags, Pessoas, Campanhas, Carrossel, Interacoes ]
Index: []

# ANÁLISE

In [13]:
# Mostrando novamente a tabela de curtidas por tag
base.groupby("Tags")[["Curtidas","Comentários"]].mean().sort_values("Curtidas",ascending=False)

                         Curtidas  Comentários
Tags
Promoções            27458.333333   531.000000
Datas comemorativas  20752.250000   343.500000
Trends               20024.000000   352.250000
Sem Tag              15347.875000   207.750000
Influenciadores      15197.285714   161.714286
Novos Produtos       10304.888889   198.555556
Dicas de como usar    6833.400000   133.600000
Produtos              6269.823529    94.117647
Loja                  2865.000000    17.666667

In [16]:
# Fazendo para Pessoas e Tag
base.groupby(["Pessoas","Tags"])[["Curtidas","Comentários"]].mean()

                                 Curtidas  Comentários
Pessoas Tags
N       Loja                  2865.000000    17.666667
        Novos Produtos        5359.000000    62.000000
        Produtos              4450.666667    60.777778
S       Datas comemorativas  20752.250000   343.500000
        Dicas de como usar    6833.400000   133.600000
        Influenciadores      15197.285714   161.714286
        Novos Produtos       10923.125000   215.625000
        Produtos              8316.375000   131.625000
        Promoções            27458.333333   531.000000
        Sem Tag              15347.875000   207.750000
        Trends               20024.000000   352.250000

In [17]:
# Também podemos ordenar por curtidas
base.groupby(["Pessoas","Tags"])[["Curtidas","Comentários"]].mean().sort_values("Curtidas", ascending=False)

                                 Curtidas  Comentários
Pessoas Tags
S       Promoções            27458.333333   531.000000
        Datas comemorativas  20752.250000   343.500000
        Trends               20024.000000   352.250000
        Sem Tag              15347.875000   207.750000
        Influenciadores      15197.285714   161.714286
        Novos Produtos       10923.125000   215.625000
        Produtos              8316.375000   131.625000
        Dicas de como usar    6833.400000   133.600000
N       Novos Produtos        5359.000000    62.000000
        Produtos              4450.666667    60.777778
        Loja                  2865.000000    17.666667

In [18]:
# Fazendo para Campanhas e Tag
base.groupby(["Campanhas","Tags"])[["Curtidas","Comentários"]].mean().sort_values("Curtidas", ascending=False)

                                   Curtidas  Comentários
Campanhas Tags
S         Promoções            33217.500000   490.500000
          Trends               22400.666667   386.666667
          Datas comemorativas  20752.250000   343.500000
          Influenciadores      18715.400000   197.600000
          Sem Tag              16850.750000   257.750000
N         Promoções            15940.000000   612.000000
          Sem Tag              13845.000000   157.750000
          Trends               12894.000000   249.000000
S         Novos Produtos       11040.666667   323.000000
N         Novos Produtos        9937.000000   136.333333
S         Produtos              9074.000000    67.500000
N         Dicas de como usar    6833.400000   133.600000
          Influenciadores       6402.000000    72.000000
          Produtos              5895.933333    97.666667
          Loja                  2865.000000    17.666667

## Conclusões
- **Ter o rosto de outras pessoas é fundamental para um bom engajamento na publicação**
    - Em todas as tags, quando havia o rosto, o resultado foi muito melhor
- **Criar campanhas ajuda muito na divulgação da marca**
- **Promoções tiveram um desempenho absurdamente maior que qualquer outra tag**
    - Porém é uma tag que pode ter custo para a loja, o que deve ser analisado
- **Usar conteúdos que estão em trend também ajudam na divulgação da marca, mesmo a trend sendo de outros nichos**
- **A melhor maneira de mostrar produtos é através de outras pessoas utilizando-os, e se possível em campanhas de datas especiais**
- **Para novos produtos a inclusão de pessoas é mais crítica ainda, sendo quase o dobro quando há um rosto junto ao produto**
- **Não podemos afirmar que a tag `Loja` é ruim até testarmos essa tag incluindo pessoas ou em uma campanha. Vale o teste para verificar**
- **Continuaremos a monitorar as postagens para encontrar novos padrões dado que ainda temos poucas informações da base**